
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_NUMBER VARCHAR(50) NOT NULL
);

CREATE TABLE OPERATION_TYPES (
    OPERATION_TYPE_ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL
);

INSERT INTO OPERATION_TYPES (OPERATION_TYPE_ID, DESCRIPTION) VALUES
(1, 'NormalPurchase'),
(2, 'PurchaseWithInstallments'),
(3, 'Withdrawal'),
(4, 'CreditVoucher');


CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_ID BIGINT NOT NULL,
    OPERATION_TYPE_ID INT NOT NULL,
    AMOUNT DECIMAL(5,2) NOT NULL,
    EVENT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_TX_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNTS(ACCOUNT_ID),

    CONSTRAINT FK_TX_OPERATION
        FOREIGN KEY (OPERATION_TYPE_ID)
        REFERENCES OPERATION_TYPES(OPERATION_TYPE_ID)
);
